name: FreeBSD

on: [push]

jobs:
  testfreebsd:
    runs-on: macos-10.15
    name: A job to run test FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      - name: uses install-with-cpanm
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: "cpanfile"
          sudo: false
      # REF: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md (see link above, at the time of writing we get Perl 5.34.0 with macOS 10.15)
      - name: perl -V
        run: |
          freebsd-version
          perl -V
      - name: Run Tests
        run: |
          perl Makefile.PL
          make
          make test
