name: linux

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.10-buster'
          - '5.12-buster'
          - '5.14-buster'
          - '5.16-buster'
          - '5.18-buster'
          - '5.20-buster'
          - '5.22-buster'
          - '5.24-buster'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1
      - name: uses install-with-cpanm
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: "cpanfile"
          sudo: false
      - name: Install Dependencies
        run: |
          apt-get install make gcc libssl-dev;
      - name: Build Module
        run: |
          perl Makefile.PL;
          make
      - name: Run Tests
        run: prove -lr -l -b -I inc t
